CREATE SEQUENCE public.invoice_no_seq AS bigint START WITH 1 INCREMENT BY 1 NO CYCLE;

CREATE TABLE public.users (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username varchar(64) NOT NULL UNIQUE,
    password_hash varchar(255) NOT NULL,
    role varchar(16) NOT NULL CHECK (role IN ('admin', 'staff')),
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.customers (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(200) NOT NULL CHECK (length(btrim(name)) > 0),
    email varchar(320) UNIQUE,
    phone varchar(40),
    address text,
    tax_code varchar(32),
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.invoices (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_no varchar(32) UNIQUE,
    customer_id bigint NOT NULL REFERENCES public.customers(id) ON DELETE RESTRICT,
    status varchar(24) NOT NULL DEFAULT 'DRAFT'
        CHECK (status IN ('DRAFT', 'ISSUED', 'PARTIALLY_PAID', 'PAID', 'CANCELLED')),
    currency char(3) NOT NULL DEFAULT 'VND',
    issue_date date,
    due_date date NOT NULL,
    tax_rate numeric(5, 4) NOT NULL DEFAULT 0
        CHECK (tax_rate BETWEEN 0 AND 0.20),
    subtotal numeric(14, 2) NOT NULL DEFAULT 0 CHECK (subtotal >= 0),
    tax_amount numeric(14, 2) NOT NULL DEFAULT 0 CHECK (tax_amount >= 0),
    total numeric(14, 2) NOT NULL DEFAULT 0 CHECK (total >= 0),
    paid_total numeric(14, 2) NOT NULL DEFAULT 0 CHECK (paid_total >= 0 AND paid_total <= total),
    cancel_reason text,
    created_by bigint NOT NULL REFERENCES public.users(id) ON DELETE RESTRICT,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT invoices_due_date_after_issue CHECK (
        issue_date IS NULL OR due_date >= issue_date
    ),
    CONSTRAINT invoices_issued_have_number CHECK (
        status NOT IN ('ISSUED', 'PARTIALLY_PAID', 'PAID') OR invoice_no IS NOT NULL
    ),
    CONSTRAINT invoices_cancel_requires_reason CHECK (
        status <> 'CANCELLED' OR (cancel_reason IS NOT NULL AND length(btrim(cancel_reason)) > 0)
    )
);

CREATE TABLE public.invoice_items (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id bigint NOT NULL REFERENCES public.invoices(id) ON DELETE CASCADE,
    description varchar(500) NOT NULL CHECK (length(btrim(description)) > 0),
    quantity numeric(12, 3) NOT NULL CHECK (quantity > 0),
    unit_price numeric(14, 2) NOT NULL CHECK (unit_price >= 0),
    line_total numeric(14, 2) NOT NULL CHECK (line_total >= 0)
);

CREATE TABLE public.payments (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id bigint NOT NULL REFERENCES public.invoices(id) ON DELETE RESTRICT,
    amount numeric(14, 2) NOT NULL CHECK (amount > 0),
    method varchar(24) NOT NULL CHECK (method IN ('CASH', 'BANK_TRANSFER', 'CARD')),
    paid_at date NOT NULL,
    reference varchar(120),
    recorded_by bigint NOT NULL REFERENCES public.users(id) ON DELETE RESTRICT,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.user_sessions (
    sid varchar NOT NULL PRIMARY KEY,
    sess json NOT NULL,
    expire timestamp(6) NOT NULL
);

CREATE INDEX invoices_customer_id_idx ON public.invoices(customer_id);
CREATE INDEX invoices_status_idx ON public.invoices(status);
CREATE INDEX invoices_due_date_idx ON public.invoices(due_date);
CREATE INDEX invoice_items_invoice_id_idx ON public.invoice_items(invoice_id);
CREATE INDEX payments_invoice_id_idx ON public.payments(invoice_id);
CREATE INDEX user_sessions_expire_idx ON public.user_sessions(expire);